# Generated by Django 3.1.7 on 2021-04-21 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodVegan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(db_column='Hello', max_length=100, verbose_name='DishName')),
                ('food_amount', models.IntegerField(verbose_name='Quantity')),
                ('food_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date-Time')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='FoodNon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(db_column='Hello', max_length=100, verbose_name='DishName')),
                ('food_amount', models.IntegerField(verbose_name='Quantity')),
                ('food_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date-Time')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(db_column='Hello', max_length=100, verbose_name='DishName')),
                ('food_amount', models.IntegerField(verbose_name='Quantity')),
                ('food_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date-Time')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
